### ISSUE TITLE
supprimer

### ISSUE THREAD

**Issue by adebeo** [demainchezmoi/plum#2]
ajouter la possibilité de désactiver un terrain

**Comment by Alexandre-Herve** [comment]
On peut supprimer un terrain.
Tu entends quoi par désactiver ?

**Comment by adebeo** [comment]
il est plus dans la liste de l'index

Très cordialement


---------------------------------------------
Denis Bolomier
Sketchup Hero
www.adebeo.com
denis@adebeo.com
--------------------------------------------

2017-10-23 18:31 GMT+02:00 Alexandre Hervé <notifications@github.com>:

**Comment by Alexandre-Herve** [comment]
Tu voudrais qu'un terrain ne soit pas supprimé mais n'apparaisse plus dans la liste ?
